//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icisleriKutuphaneWeb.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class icisleriBakanlıgıWebEntities : DbContext
    {
        public icisleriBakanlıgıWebEntities()
            : base("name=icisleriBakanlıgıWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBHAREKET> TBHAREKET { get; set; }
        public virtual DbSet<TBKITAP> TBKITAP { get; set; }
        public virtual DbSet<TBPERSONEL> TBPERSONEL { get; set; }
        public virtual DbSet<TBUYELER> TBUYELER { get; set; }
        public virtual DbSet<TBILETISIM> TBILETISIM { get; set; }
        public virtual DbSet<TBDUYURULAR> TBDUYURULAR { get; set; }
        public virtual DbSet<TBMESAJ> TBMESAJ { get; set; }
        public virtual DbSet<TBDERGI> TBDERGI { get; set; }
        public virtual DbSet<TBKAYITDISI> TBKAYITDISI { get; set; }
    }
}
