//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icisleriKutuphaneWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBDERGI
    {
        public int ID { get; set; }
        public string eser { get; set; }
        public string Sorumlular { get; set; }
        public string demirbas { get; set; }
        public string issn { get; set; }
        public string yayinYeri { get; set; }
        public string yayinlayan { get; set; }
        public string matbaa { get; set; }
        public string fizikselNiteleme { get; set; }
        public string altTur { get; set; }
        public Nullable<System.DateTime> kayitTarih { get; set; }
        public Nullable<System.DateTime> yayinTarih { get; set; }
        public Nullable<int> kopya { get; set; }
        public string dilBir { get; set; }
        public string diliki { get; set; }
        public string temelGiris { get; set; }
        public string aramaGrubu { get; set; }
        public string oda { get; set; }
        public string durum { get; set; }
        public string sekil { get; set; }
        public string baslik { get; set; }
        public string sureliAyrinti { get; set; }
        public string URLadres { get; set; }
        public string MarcEkGiris { get; set; }
    }
}
