//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icisleriKutuphaneWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBKITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBKITAP()
        {
            this.TBHAREKET = new HashSet<TBHAREKET>();
        }
    
        public int ID { get; set; }
        public string eser { get; set; }
        public string yazar { get; set; }
        public string demirbas { get; set; }
        public string isbn { get; set; }
        public string yayinYeri { get; set; }
        public string yayinlayan { get; set; }
        public string matbaa { get; set; }
        public string fizikselNiteleme { get; set; }
        public string yerNumarasi { get; set; }
        public Nullable<System.DateTime> kayitTarih { get; set; }
        public Nullable<System.DateTime> yayinTarih { get; set; }
        public Nullable<int> kopya { get; set; }
        public Nullable<int> cilt { get; set; }
        public string dilBir { get; set; }
        public string diliki { get; set; }
        public Nullable<bool> durum { get; set; }
        public string sorumlular { get; set; }
        public string altTur { get; set; }
        public string temelGiris { get; set; }
        public string aramaGrubu { get; set; }
        public string saglama { get; set; }
        public string oda { get; set; }
        public string konuBasliklari { get; set; }
        public string kitabiKayitEden { get; set; }
        public string notlar { get; set; }
        public string degisiklikYapan { get; set; }
        public string kitapResim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBHAREKET> TBHAREKET { get; set; }
    }
}
