//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icisleriKutuphaneWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPERSONEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBPERSONEL()
        {
            this.TBHAREKET = new HashSet<TBHAREKET>();
        }
    
        public int ID { get; set; }
        public string personelAdSoyad { get; set; }
        public string personelTcNumarasi { get; set; }
        public string personelTelefon { get; set; }
        public string personelEmail { get; set; }
        public string personelAdres { get; set; }
        public string personelKullaniciAd { get; set; }
        public string personelSifre { get; set; }
        public string personelUnvan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBHAREKET> TBHAREKET { get; set; }
    }
}
