//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icisleriKutuphaneWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUYELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBUYELER()
        {
            this.TBHAREKET = new HashSet<TBHAREKET>();
        }
    
        public int ID { get; set; }
        public string uyeAdSoyad { get; set; }
        public string uyeTcNumarasi { get; set; }
        public string uyeTelefon { get; set; }
        public string uyeEmail { get; set; }
        public string uyeAdres { get; set; }
        public string calistigiBirim { get; set; }
        public string unvan { get; set; }
        public string isTelefonu { get; set; }
        public string durum { get; set; }
        public string oduncNot { get; set; }
        public string fotograf { get; set; }
        public string uyeKullaniciAd { get; set; }
        public string uyeSifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBHAREKET> TBHAREKET { get; set; }
    }
}
